site_name: Northumbria University Research Computing Community
site_description: Documentation, events and newsletter for Northumbria University's Research Computing Community

site_url: https://rsc-northumbria.github.io/oswald-docs/ # Needed for rss-plugin
repo_url: https://github.com/RSC-Northumbria/oswald-docs 
repo_name: RSC-Northumbria/oswald-docs
edit_uri: edit/main/docs/

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - rss:
      abstract_chars_count: 10000 # Probably the whole newsletter, but truncate if quite long
      image: https://rsc-northumbria.github.io/oswald-docs/assets/images/logo.png
      match_path: "newsletter/.*"
      pretty_print: true

theme:
  name: material

  locale: en
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  custom_dir: theme/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - Home: index.md

  - Oswald Documentation:
    - What is Oswald?: oswald/what-is-oswald.md

    - Quickstart:
      - Accessing Oswald: oswald/quickstart/accessing-oswald.md
      - Storage and Filesystems: oswald/quickstart/storage-and-filesystems.md
      - Software Environment and Modules: oswald/quickstart/software-environment.md
      - Running Jobs: oswald/quickstart/running-jobs.md
      - Using Specialised Nodes: oswald/quickstart/using-specialised-nodes.md
      - Application Development Tools: oswald/quickstart/application-development-tools.md

    - Software:
      - Software List: oswald/software/software-list.md
      - MPI: oswald/software/mpi.md
      - GNU Compilers: oswald/software/gnu-compilers.md
      - Intel Compilers: oswald/software/intel-compilers.md

    - Support:
      - University Support: oswald/support/university-support.md
      - FAQs: oswald/support/faqs.md
      - Known Issues: oswald/support/known-issues.md

  - Events:
    - All Events: events/events.md

  - Newsletter:
    - Sign Up: newsletter/signup.md
    - 2021:
      - October: newsletter/2021-10.md
