site_name: Northumbria University Research Computing Community
site_description: Documentation, events and newsletter for Northumbria University's Research Computing Community

site_url: https://rsc-northumbria.github.io/oswald-docs/ # Needed for rss-plugin
repo_url: https://github.com/RSC-Northumbria/oswald-docs 
repo_name: RSC-Northumbria/oswald-docs
edit_uri: edit/main/docs/

plugins:
  - search
  - git-revision-date-localized:
      enable_creation_date: true
  - rss:
      abstract_chars_count: 10000 # Probably the whole newsletter, but truncate if quite long
      image: https://rsc-northumbria.github.io/oswald-docs/assets/images/logo.png
      match_path: "newsletter/.*"
      pretty_print: true

theme:
  name: material

  locale: en
  logo: assets/images/logo.png
  favicon: assets/images/logo.png
  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.expand

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: deep purple
      accent: amber
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: deep purple
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  custom_dir: theme/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: true

nav:
  - Home: index.md

  - Quickstart:
    - Accessing Oswald: quickstart/accessing-oswald.md
    - Storage and Filesystems: quickstart/storage-and-filesystems.md
    - Software Environment and Modules: quickstart/software-environment.md
    - Running Jobs: quickstart/running-jobs.md
    - Using Specialised Nodes: quickstart/using-specialised-nodes.md
    - Application Development Tools: quickstart/application-development-tools.md

  - Software:
    - Software List: software/software-list.md
    - MPI: software/mpi.md
    - GNU Compilers: software/gnu-compilers.md
    - Intel Compilers: software/intel-compilers.md

  - Support:
    - University Support: support/university-support.md
    - FAQs: support/faqs.md
    - Known Issues: support/known-issues.md
